### ISSUE TITLE
Lack of example and context in use of this parameter. Should we include https:// in the audience ? 

### ISSUE THREAD

**Issue by jpla-csm** [Cosmo-Tech/azure-sample-webapp#762]
https://github.com/Cosmo-Tech/azure-sample-webapp/blob/35f29f7728377f5ffd5711a98b986e5766ba79b2/doc/powerBI.md?plain=1#L645

**Comment by csm-thu** [comment]
Hello !
The expected value is an [application id](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/application-properties#application-id), an identifier value with a pattern like `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`. You can find this value in the Azure portal, in the _Overview_ blade of the Cosmo Tech API application that your webapp instance uses.

The goal of this parameter is to validate the tokens of requests received by the Azure Function, based on the value of the `aud` field in [id tokens](https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims).

We'll add more information and an example in the documentation, thank you for the feedback :slightly_smiling_face:

**Comment by csm-thu** [comment]
More details have been [added in the documentation](https://github.com/Cosmo-Tech/azure-sample-webapp/commit/7af778b4eb7d0aa18278ca7b8823636d7091e636)
Closing this issue
